
Simulation did not find a sound architecture.

Simulation did not find a sound architecture.

Simulation did not find a sound architecture.

Simulation did not find a sound architecture.
Traceback (most recent call last):
  File "evolution.py", line 393, in <module>
    main()
  File "evolution.py", line 377, in main
    evo_vars = run_evolution(output_dir, genome_tracker_new, genome_tracker_old, target_df, arguments, all_rmse_list, max_rmse)
  File "evolution.py", line 269, in run_evolution
    rmse_new = mutation_analysis.analyze_mutation(genome_tracker_new, output_dir, target_df, arguments.args.replicate_mutation_number, 1, arguments.args.dynamic_deg_rate)
  File "./lib/mutation_analysis.py", line 38, in analyze_mutation
    save_df['time'] = save_df['time'].round().astype(int)
  File "/home/sahil/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 1999, in round
    result = com.values_from_object(self).round(decimals)
AttributeError: 'str' object has no attribute 'rint'
Traceback (most recent call last):
  File "evolution.py", line 393, in <module>
    main()
  File "evolution.py", line 377, in main
    evo_vars = run_evolution(output_dir, genome_tracker_new, genome_tracker_old, target_df, arguments, all_rmse_list, max_rmse)
  File "evolution.py", line 269, in run_evolution
    rmse_new = mutation_analysis.analyze_mutation(genome_tracker_new, output_dir, target_df, arguments.args.replicate_mutation_number, 1, arguments.args.dynamic_deg_rate)
  File "./lib/mutation_analysis.py", line 37, in analyze_mutation
    save_df = pd.read_csv(output_dir+"expression_pattern.tsv", header=0, sep='\t')
  File "/home/sahil/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/sahil/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 435, in _read
    data = parser.read(nrows)
  File "/home/sahil/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1139, in read
    ret = self._engine.read(nrows)
  File "/home/sahil/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1995, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 899, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 914, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 968, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 955, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2172, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 5 fields in line 2227, saw 6

Traceback (most recent call last):
  File "evolution.py", line 393, in <module>
    main()
  File "evolution.py", line 377, in main
    evo_vars = run_evolution(output_dir, genome_tracker_new, genome_tracker_old, target_df, arguments, all_rmse_list, max_rmse)
  File "evolution.py", line 269, in run_evolution
    rmse_new = mutation_analysis.analyze_mutation(genome_tracker_new, output_dir, target_df, arguments.args.replicate_mutation_number, 1, arguments.args.dynamic_deg_rate)
  File "./lib/mutation_analysis.py", line 37, in analyze_mutation
    save_df = pd.read_csv(output_dir+"expression_pattern.tsv", header=0, sep='\t')
  File "/home/sahil/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/sahil/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 435, in _read
    data = parser.read(nrows)
  File "/home/sahil/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1139, in read
    ret = self._engine.read(nrows)
  File "/home/sahil/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1995, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 899, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 914, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 968, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 955, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2172, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 5 fields in line 3441, saw 8

Traceback (most recent call last):
  File "/home/sahil/anaconda3/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 172, in save
    self._save()
  File "/home/sahil/anaconda3/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 288, in _save
    self._save_chunk(start_i, end_i)
  File "/home/sahil/anaconda3/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 315, in _save_chunk
    self.cols, self.writer)
  File "pandas/_libs/writers.pyx", line 72, in pandas._libs.writers.write_csv_rows
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "evolution.py", line 393, in <module>
    main()
  File "evolution.py", line 377, in main
    evo_vars = run_evolution(output_dir, genome_tracker_new, genome_tracker_old, target_df, arguments, all_rmse_list, max_rmse)
  File "evolution.py", line 280, in run_evolution
    save_df.to_csv(output_dir+"expression_pattern_{}.tsv".format(i), sep='\t', index=False)
  File "/home/sahil/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 3020, in to_csv
    formatter.save()
  File "/home/sahil/anaconda3/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 187, in save
    f.close()
OSError: [Errno 28] No space left on device

Simulation did not find a sound architecture.

Simulation did not find a sound architecture.

Simulation did not find a sound architecture.

Simulation did not find a sound architecture.
